#!/bin/csh
#
# stop and remove any containers that exist
#
/srv/persistent-data/docker-scripts/stop
#
/srv/persistent-data/docker-scripts/run-nginx
/srv/persistent-data/docker-scripts/run-docker-gen
/srv/persistent-data/docker-scripts/run-mysql
/srv/persistent-data/docker-scripts/run-mapping-00

