#!/bin/bash
#
# run the monitoring instance at port 443 first
#
        echo ipynb-az-06.oit.duke.edu:443
        sudo docker run --name jupyter-test-$port \
          --link mysqlserver\:jupyter-test-443 \
          -d -p 127.0.0.1\:\:8888 \
          -e PASSWORD=JIyPaGrQzxH3taTc9PS9aW4mB8CxkR \
          -e VIRTUAL_HOST=ipynb-az-06.oit.duke.edu\:443 \
          -e MAP_VIRTUAL_PORT=443 \
          -v /srv/persistent-data/homedirs/monitoring-user\:/home/jovyan/work \
          -e NB_UID=1000 \
          -t jupyter-sta663
#
# now loop through the actual user mappings
#
INPUT=/srv/persistent-data/docker-scripts/mapping-00
OLDIFS=$IFS
IFS=,
[ ! -f $INPUT ] && { echo "$INPUT file not found"; exit 99; }
while read port pw
do
        echo ipynb-az-06.oit.duke.edu:40$port
        sudo docker run --name jupyter-$port \
          --link mysqlserver\:jupyter-test-443 \
          -d -p 127.0.0.1\:\:8888 \
          -e PASSWORD=$pw \
          -e VIRTUAL_HOST=ipynb-az-06.oit.duke.edu\:40$port \
          -e MAP_VIRTUAL_PORT=40$port \
          -v /srv/persistent-data/homedirs/user$port\:/home/jovyan/work \
          -e NB_UID=1000 \
          -t jupyter-sta663 

        sleep 3
done < $INPUT
IFS=$OLDIFS

